title: "Train Graffiti"
tagline: "A jekyll theme that looks like a shell/terminal"
description: "A small train project for fun, all train graffiti images."
github_username: C0DE33301
baseurl: "/Train-Graffiti"
url: "https://C0DE33301.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - slideshow.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
